package gr.bouzas.businessapp;

import java.time.LocalDate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Person {
    
    private String name;
    private String surname;
    // field generated by DMN
    private String fullname;

    private LocalDate dob;
    // field generated by DMN
    private Integer age;

}
